#pragma checksum "D:\Program Files\findle\ASP.NETFindle\ASP.NETFindle\Views\Display\SearchLocation.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "b0602b2a6dee8dd80fe350a93700f1bc03cac0e4"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Display_SearchLocation), @"mvc.1.0.view", @"/Views/Display/SearchLocation.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "D:\Program Files\findle\ASP.NETFindle\ASP.NETFindle\Views\_ViewImports.cshtml"
using ASP.NETFindle;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\Program Files\findle\ASP.NETFindle\ASP.NETFindle\Views\_ViewImports.cshtml"
using ASP.NETFindle.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"b0602b2a6dee8dd80fe350a93700f1bc03cac0e4", @"/Views/Display/SearchLocation.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"50a8dd4843e3e9f3dd035a23e2b3dcfce3137625", @"/Views/_ViewImports.cshtml")]
    public class Views_Display_SearchLocation : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<ASP.NETFindle.Models.User>
    {
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper;
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 1 "D:\Program Files\findle\ASP.NETFindle\ASP.NETFindle\Views\Display\SearchLocation.cshtml"
  
    ViewData["Title"] = "Search location";

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n");
            WriteLiteral("\r\n<h1>User location</h1>\r\n\r\n");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("head", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "b0602b2a6dee8dd80fe350a93700f1bc03cac0e43568", async() => {
                WriteLiteral("\r\n\r\n");
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n\r\n");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("body", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "b0602b2a6dee8dd80fe350a93700f1bc03cac0e44542", async() => {
                WriteLiteral("\r\n");
#nullable restore
#line 14 "D:\Program Files\findle\ASP.NETFindle\ASP.NETFindle\Views\Display\SearchLocation.cshtml"
      
        var targetUser = ViewData["targetUser"] as ASP.NETFindle.Models.User;
    

#line default
#line hidden
#nullable disable
                WriteLiteral("\r\n    <div>\r\n        Naam: ");
#nullable restore
#line 19 "D:\Program Files\findle\ASP.NETFindle\ASP.NETFindle\Views\Display\SearchLocation.cshtml"
         Write(targetUser.Firstname);

#line default
#line hidden
#nullable disable
                WriteLiteral(" ");
#nullable restore
#line 19 "D:\Program Files\findle\ASP.NETFindle\ASP.NETFindle\Views\Display\SearchLocation.cshtml"
                               Write(targetUser.Lastname);

#line default
#line hidden
#nullable disable
                WriteLiteral("\r\n    </div>\r\n    <div>\r\n        Location: ");
#nullable restore
#line 22 "D:\Program Files\findle\ASP.NETFindle\ASP.NETFindle\Views\Display\SearchLocation.cshtml"
             Write(targetUser.location_Id);

#line default
#line hidden
#nullable disable
                WriteLiteral("\r\n    </div>\r\n    <div>\r\n        Email: ");
#nullable restore
#line 25 "D:\Program Files\findle\ASP.NETFindle\ASP.NETFindle\Views\Display\SearchLocation.cshtml"
          Write(targetUser.Email);

#line default
#line hidden
#nullable disable
                WriteLiteral("\r\n    </div>\r\n    <div>\r\n        Profile: ");
#nullable restore
#line 28 "D:\Program Files\findle\ASP.NETFindle\ASP.NETFindle\Views\Display\SearchLocation.cshtml"
            Write(targetUser.Profile);

#line default
#line hidden
#nullable disable
                WriteLiteral("\r\n    </div>\r\n    <div>\r\n        Functie: ");
#nullable restore
#line 31 "D:\Program Files\findle\ASP.NETFindle\ASP.NETFindle\Views\Display\SearchLocation.cshtml"
            Write(targetUser.UserFunction);

#line default
#line hidden
#nullable disable
                WriteLiteral("\r\n    </div>\r\n    <div>\r\n\r\n    </div>\r\n");
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<ASP.NETFindle.Models.User> Html { get; private set; }
    }
}
#pragma warning restore 1591
